version: '3.8'

volumes:
  neo4jdata:

services:
  neo4j:
    image: neo4j:5.18.1
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/r@ndomp4ss
    networks:
      - backend
    volumes:
      - neo4jdata:/data
      - neo4jdata:/logs

networks:
  backend:
    driver: bridge